/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/common/AlertDialog.vue')['default']
    AuthLayout: typeof import('./src/components/auth/AuthLayout.vue')['default']
    AuthSlider: typeof import('./src/components/auth/AuthSlider.vue')['default']
    DiaryCommentModal: typeof import('./src/components/modal/DiaryCommentModal.vue')['default']
    DiaryFeedItem: typeof import('./src/components/home/DiaryFeedItem.vue')['default']
    FollowingPanel: typeof import('./src/components/home/FollowingPanel.vue')['default']
    FriendsListModal: typeof import('./src/components/log/FriendsListModal.vue')['default']
    KakaoMap: typeof import('./src/components/common/KakaoMap.vue')['default']
    LogAiAnalysis: typeof import('./src/components/log/LogAiAnalysis.vue')['default']
    LogCalendarWidget: typeof import('./src/components/log/LogCalendarWidget.vue')['default']
    LogCard: typeof import('./src/components/log/LogCard.vue')['default']
    LogContentTabs: typeof import('./src/components/log/LogContentTabs.vue')['default']
    LogMapWidget: typeof import('./src/components/log/LogMapWidget.vue')['default']
    MyPageProfile: typeof import('./src/components/log/MyPageProfile.vue')['default']
    PlaceDetailModal: typeof import('./src/components/modal/PlaceDetailModal.vue')['default']
    PlaceDetailPanel: typeof import('./src/components/trip/PlaceDetailPanel.vue')['default']
    ProfileImageModal: typeof import('./src/components/log/ProfileImageModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/components/common/ScrollToTop.vue')['default']
    TravelNavbar: typeof import('./src/components/common/TravelNavbar.vue')['default']
    TripCard: typeof import('./src/components/trip/TripCard.vue')['default']
    TripDetailModal: typeof import('./src/components/modal/TripDetailModal.vue')['default']
    TripPlanHeader: typeof import('./src/components/trip/TripPlanHeader.vue')['default']
    TripPlanPanel: typeof import('./src/components/trip/TripPlanPanel.vue')['default']
    TripSearchListPanel: typeof import('./src/components/trip/TripSearchListPanel.vue')['default']
  }
}
